d3.select("#header")
    .append("a")
    .attr("id", "header-title")
    .attr("href", "https://diffusion.ikiwi.cc/")
    .append("img")
    .attr("id", "header-logo")
    .attr("src", "./icons/logo.svg")
d3.select("#header-title")
    .append("div")
    .text("秒懂大模型 - Stable Diffusion 扩散模型原理图解")

d3.select("#header")
    .append("div")
    .attr("id", "header-message")

d3.select("#header-message")
    .append("div")
    .attr("id", "header-message-1")
    .text("了解 Stable Diffusion 如何一步步将")
d3.select("#header-message")
    .append("div")
    .attr("id", "header-message-2")
    .text("文字提示")
d3.select("#header-message")
    .append("div")
    .attr("id", "header-message-3")
    .text("转换为")
d3.select("#header-message")
    .append("div")
    .attr("id", "header-message-4")
    .text("图像")
d3.select("#header-message")
    .append("div")
    .attr("id", "header-message-5")
    .text("!")

